apiVersion: v2
name: athos
description: A production-grade Kubernetes operator for PostgreSQL
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - postgresql
  - database
  - operator
home: https://github.com/Kitio-Tek/athos-kubernetes
sources:
  - https://github.com/Kitio-Tek/athos-kubernetes

