apiVersion: v2
name: vigil-kubernetes
description: A Kubernetes operator for PostgreSQL lifecycle management
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - postgresql
  - database
  - operator
home: https://github.com/Kitio-Tek/vigil-kubernetes
sources:
  - https://github.com/Kitio-Tek/vigil-kubernetes
maintainers:
  - name: Kitio-Tek
    email: kmyriantek@gmail.com
