/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package configfile_test

import (
	"strings"
	"testing"

	"github.com/Kitio-Tek/athos-kubernetes/internal/configfile"
)

func TestPostgreSQLConf_SortedOutput(t *testing.T) {
	params := map[string]string{
		"wal_level":        "replica",
		"listen_addresses": "*",
		"max_connections":  "200",
	}
	out := configfile.PostgreSQLConf(params)
	lines := strings.Split(strings.TrimSpace(out), "\n")

	// Find non-comment, non-blank lines.
	paramLines := make([]string, 0, len(lines))
	for _, l := range lines {
		if l == "" || strings.HasPrefix(l, "#") {
			continue
		}
		paramLines = append(paramLines, l)
	}
	if len(paramLines) != 3 {
		t.Fatalf("expected 3 param lines, got %d: %v", len(paramLines), paramLines)
	}
	// Should be alphabetically sorted.
	if !strings.HasPrefix(paramLines[0], "listen_addresses") {
		t.Errorf("first param should be listen_addresses, got: %q", paramLines[0])
	}
	if !strings.HasPrefix(paramLines[1], "max_connections") {
		t.Errorf("second param should be max_connections, got: %q", paramLines[1])
	}
	if !strings.HasPrefix(paramLines[2], "wal_level") {
		t.Errorf("third param should be wal_level, got: %q", paramLines[2])
	}
}

func TestPostgreSQLConf_QuotedValues(t *testing.T) {
	params := map[string]string{
		"archive_command": "cp %p /mnt/wal/%f",
		"max_connections": "100",
		"wal_level":       "replica",
	}
	out := configfile.PostgreSQLConf(params)

	if !strings.Contains(out, "archive_command = 'cp %p /mnt/wal/%f'") {
		t.Errorf("archive_command should be quoted, output:\n%s", out)
	}
	if !strings.Contains(out, "max_connections = 100") {
		t.Errorf("max_connections should not be quoted, output:\n%s", out)
	}
}

func TestPostgreSQLConf_BooleanNotQuoted(t *testing.T) {
	params := map[string]string{
		"hot_standby": "on",
		"ssl":         "off",
	}
	out := configfile.PostgreSQLConf(params)

	if strings.Contains(out, "'on'") || strings.Contains(out, "'off'") {
		t.Errorf("boolean values should not be quoted:\n%s", out)
	}
}

func TestPostgreSQLConf_GeneratedComment(t *testing.T) {
	out := configfile.PostgreSQLConf(map[string]string{"port": "5432"})
	if !strings.Contains(out, "Generated by Athos") {
		t.Error("expected generated-by comment in output")
	}
}

func TestPgHBAConf_ContainsRules(t *testing.T) {
	rules := configfile.DefaultRules("10.0.0.0/8")
	out := configfile.PgHBAConf(rules)

	if !strings.Contains(out, "local") {
		t.Error("expected local rule in pg_hba.conf")
	}
	if !strings.Contains(out, "replication") {
		t.Error("expected replication rule in pg_hba.conf")
	}
	if !strings.Contains(out, "scram-sha-256") {
		t.Error("expected scram-sha-256 in pg_hba.conf")
	}
}

func TestPgHBAConf_DenyAll(t *testing.T) {
	out := configfile.PgHBAConf(nil)
	if !strings.Contains(out, "reject") {
		t.Error("expected deny-all reject rule at end")
	}
}

func TestHBARule_String_Local(t *testing.T) {
	r := configfile.HBARule{
		Type:     "local",
		Database: "all",
		User:     "postgres",
		Method:   "peer",
	}
	s := r.String()
	if !strings.HasPrefix(s, "local") {
		t.Errorf("local rule should start with 'local': %q", s)
	}
	// Local rules must not contain an address field.
	parts := strings.Fields(s)
	if len(parts) != 4 {
		t.Errorf("local rule should have 4 fields, got %d: %q", len(parts), s)
	}
}

func TestHBARule_String_Host(t *testing.T) {
	r := configfile.HBARule{
		Type:     "host",
		Database: "all",
		User:     "all",
		Address:  "10.0.0.0/8",
		Method:   "scram-sha-256",
	}
	s := r.String()
	if !strings.Contains(s, "10.0.0.0/8") {
		t.Errorf("host rule should contain address: %q", s)
	}
}

func TestHBARule_String_DefaultAddress(t *testing.T) {
	r := configfile.HBARule{
		Type:     "host",
		Database: "all",
		User:     "all",
		Method:   "scram-sha-256",
	}
	s := r.String()
	if !strings.Contains(s, "0.0.0.0/0") {
		t.Errorf("missing address should default to 0.0.0.0/0: %q", s)
	}
}

func TestMergeParams_HigherPriorityWins(t *testing.T) {
	base := map[string]string{"wal_level": "minimal", "max_connections": "100"}
	override := map[string]string{"wal_level": "logical"}

	merged := configfile.MergeParams(base, override)
	if merged["wal_level"] != "logical" {
		t.Errorf("override should win: got %q", merged["wal_level"])
	}
	if merged["max_connections"] != "100" {
		t.Errorf("base value should survive: got %q", merged["max_connections"])
	}
}

func TestRequiredParams(t *testing.T) {
	p := configfile.RequiredParams(5432, 200)
	if p["listen_addresses"] != "*" {
		t.Error("listen_addresses should be *")
	}
	if p["port"] != "5432" {
		t.Errorf("port = %q, want 5432", p["port"])
	}
	if p["max_connections"] != "200" {
		t.Errorf("max_connections = %q, want 200", p["max_connections"])
	}
}

func TestWALStreamingParams(t *testing.T) {
	p := configfile.WALStreamingParams(10, 10)
	if p["wal_level"] != "replica" {
		t.Error("wal_level should be replica")
	}
	if p["hot_standby"] != "on" {
		t.Error("hot_standby should be on")
	}
}

func TestArchiveParams(t *testing.T) {
	p := configfile.ArchiveParams("pgbackrest archive-push %p")
	if p["archive_mode"] != "on" {
		t.Error("archive_mode should be on")
	}
	if p["archive_command"] != "pgbackrest archive-push %p" {
		t.Errorf("unexpected archive_command: %q", p["archive_command"])
	}
}

func TestTLSParams(t *testing.T) {
	p := configfile.TLSParams("/etc/postgresql/tls")
	if p["ssl"] != "on" {
		t.Error("ssl should be on")
	}
	if !strings.Contains(p["ssl_cert_file"], "server.crt") {
		t.Error("ssl_cert_file should point to server.crt")
	}
}
