/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package configfile provides builders for postgresql.conf and pg_hba.conf
// content rendered into Kubernetes ConfigMaps by the Vigil operator.
package configfile

import (
	"fmt"
	"sort"
	"strings"
)

// PostgreSQLConf renders a set of key/value parameters into a postgresql.conf
// formatted string. Parameters are emitted in sorted order for determinism.
func PostgreSQLConf(params map[string]string) string {
	keys := make([]string, 0, len(params))
	for k := range params {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteString("# Generated by Vigil Kubernetes operator — do not edit manually.\n")
	sb.WriteString("\n")
	for _, k := range keys {
		v := params[k]
		if needsQuote(v) {
			sb.WriteString(fmt.Sprintf("%s = '%s'\n", k, escapeValue(v)))
		} else {
			sb.WriteString(fmt.Sprintf("%s = %s\n", k, v))
		}
	}
	return sb.String()
}

// PgHBAConf renders a list of HBA rules into a pg_hba.conf string.
// Each Rule is appended in the provided order, followed by a deny-all fallback.
func PgHBAConf(rules []HBARule) string {
	var sb strings.Builder
	sb.WriteString("# Generated by Vigil Kubernetes operator — do not edit manually.\n")
	sb.WriteString("#\n")
	sb.WriteString("# TYPE  DATABASE        USER            ADDRESS                 METHOD\n")
	sb.WriteString("\n")
	for _, r := range rules {
		sb.WriteString(r.String())
		sb.WriteByte('\n')
	}
	// Implicit deny-all at the end.
	sb.WriteString("# Deny all other connections.\n")
	sb.WriteString("host    all             all             0.0.0.0/0               reject\n")
	return sb.String()
}

// HBARule represents a single line in pg_hba.conf.
type HBARule struct {
	// Type is the connection type: local, host, hostssl, hostnossl, hostgssenc.
	Type string
	// Database is the database name or "all" / "replication".
	Database string
	// User is the database role name or "all".
	User string
	// Address is the CIDR or hostname (empty for local connections).
	Address string
	// Method is the authentication method (e.g. md5, scram-sha-256, trust, peer).
	Method string
	// Options are optional method-specific options (e.g. map=mymap).
	Options string
}

// String serialises the rule into a pg_hba.conf line.
func (r HBARule) String() string {
	parts := []string{r.Type, r.Database, r.User}
	if r.Type != "local" {
		addr := r.Address
		if addr == "" {
			addr = "0.0.0.0/0"
		}
		parts = append(parts, addr)
	}
	parts = append(parts, r.Method)
	if r.Options != "" {
		parts = append(parts, r.Options)
	}
	return strings.Join(parts, "\t")
}

// DefaultRules returns the standard HBA rules applied to every cluster:
//   - Local peer for postgres superuser (for operator scripts).
//   - scram-sha-256 for all other local and host connections.
//   - Replication connections from the cluster subnet.
func DefaultRules(clusterCIDR string) []HBARule {
	return []HBARule{
		{Type: "local", Database: "all", User: "postgres", Method: "peer"},
		{Type: "local", Database: "replication", User: "postgres", Method: "peer"},
		{Type: "local", Database: "all", User: "all", Method: "scram-sha-256"},
		{Type: "host", Database: "all", User: "all", Address: "127.0.0.1/32", Method: "scram-sha-256"},
		{Type: "host", Database: "all", User: "all", Address: "::1/128", Method: "scram-sha-256"},
		{Type: "host", Database: "replication", User: "postgres", Address: clusterCIDR, Method: "scram-sha-256"},
		{Type: "host", Database: "all", User: "all", Address: clusterCIDR, Method: "scram-sha-256"},
	}
}

// MergeParams produces a final parameter map by layering sources from lowest
// to highest priority. Later maps override earlier ones.
func MergeParams(sources ...map[string]string) map[string]string {
	result := make(map[string]string)
	for _, src := range sources {
		for k, v := range src {
			result[k] = v
		}
	}
	return result
}

// RequiredParams returns postgresql.conf parameters that the operator always
// enforces and that user-supplied values cannot override.
func RequiredParams(port int, maxConn int) map[string]string {
	return map[string]string{
		"listen_addresses":               "*",
		"port":                           fmt.Sprintf("%d", port),
		"max_connections":                fmt.Sprintf("%d", maxConn),
		"superuser_reserved_connections": "3",
		"logging_collector":              "off",
		"log_destination":                "stderr",
	}
}

// WALStreamingParams returns parameters required for WAL streaming replication.
func WALStreamingParams(maxWALSenders, maxSlots int) map[string]string {
	return map[string]string{
		"wal_level":             "replica",
		"max_wal_senders":       fmt.Sprintf("%d", maxWALSenders),
		"max_replication_slots": fmt.Sprintf("%d", maxSlots),
		"hot_standby":           "on",
		"hot_standby_feedback":  "on",
	}
}

// ArchiveParams returns parameters for WAL archiving to an external store.
// archiveCmd is the shell command invoked by PostgreSQL to archive a WAL segment
// (e.g. "pgbackrest --stanza=main archive-push %p").
func ArchiveParams(archiveCmd string) map[string]string {
	return map[string]string{
		"archive_mode":    "on",
		"archive_command": archiveCmd,
		"archive_timeout": "300",
	}
}

// TLSParams returns postgresql.conf parameters that enable TLS, pointing at
// the certificate and key files under certDir.
func TLSParams(certDir string) map[string]string {
	return map[string]string{
		"ssl":           "on",
		"ssl_cert_file": certDir + "/server.crt",
		"ssl_key_file":  certDir + "/server.key",
	}
}

// needsQuote reports whether a postgresql.conf value must be single-quoted.
// Values containing spaces, special characters, or that look non-numeric
// require quoting.
func needsQuote(v string) bool {
	if v == "" {
		return true
	}
	// Unquoted booleans and numeric values are fine.
	switch strings.ToLower(v) {
	case "on", "off", "true", "false", "yes", "no":
		return false
	}
	for _, c := range v {
		if c == ' ' || c == '\t' || c == '\'' || c == '"' || c == '#' || c == '\\' {
			return true
		}
	}
	// Values that are purely numeric (possibly with a unit suffix) don't need quoting.
	allNumeric := true
	for _, c := range v {
		if !isDigitOrUnit(c) {
			allNumeric = false
			break
		}
	}
	return !allNumeric
}

func isDigitOrUnit(c rune) bool {
	return (c >= '0' && c <= '9') || c == '.' || c == '-' ||
		c == 'k' || c == 'K' || c == 'M' || c == 'G' || c == 'B' || c == 's' || c == 'm' || c == 'h' || c == 'd'
}

// escapeValue escapes single-quotes inside a postgresql.conf value by doubling them.
func escapeValue(v string) string {
	return strings.ReplaceAll(v, "'", "''")
}
