apiVersion: v2
name: athos-kubernetes
description: A Kubernetes operator for PostgreSQL lifecycle management
type: application
version: 0.5.0
appVersion: "0.5.0"
keywords:
  - postgresql
  - database
  - operator
home: https://github.com/Kitio-Tek/athos-kubernetes
sources:
  - https://github.com/Kitio-Tek/athos-kubernetes

